apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: microservice
  template:
    metadata:
      labels:
        app: microservice
    spec:
      containers:
      - name: microservice
        image: 20150748/micro-app:db451f1e251d730ff3f8eff4a06365bafe00ad8f
        ports:
        - containerPort: 5000
