apiVersion: v1
kind: Service
metadata:
  name: microservice-service
spec:
  selector:
    app: microservice
  ports:
  - protocol: TCP
    port: 5000  
    targetPort: 5000  
  type: LoadBalancer  