name: Apply k8s Deployments
on:
  push:
    branches:
      - main

jobs:
  
  deploy:
    name: Deploy to EKS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Kubernetes Manifests
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Update kubeconfig
        run: |
              aws eks --region us-west-2 update-kubeconfig --name stage-eks-cluster

      - name: Trigger app deployment
        uses: statsig-io/kubectl-via-eksctl@main
        env:
            aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            region: us-west-2
            cluster: stage-eks-cluster

      - name: Deploy Kubernetes Manifests
        run: |
          kubectl apply -f deployment.yml  
          kubectl apply -f service.yml
        working-directory: ./kubernetes

      - name: Verify Deployment
        run: |
          kubectl get pods
          kubectl get svc microservice-service


     
   
  