name: Microservice pipeline App
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
    containerization:
        runs-on: Microservices-runner
        steps:
            - name: checkout config files
              uses: actions/checkout@v2
            - name: docker hub login
              uses: docker/login-action@v3
              with:
                username: ${{ vars.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_PASSWORD }}

            - name: install Dependancies
              run: |
                    chmod +x install_dep.sh
                    ./install_dep.sh

            - name: Build and push
              uses: docker/build-push-action@v5
              with:
                  context: .
                  push: false
                  tags: ${{ vars.DOCKERHUB_USERNAME }}/micro-app:${{ github.sha }}
  
  
            - name: Docker image Test
              run: |
                   docker images
                   docker run --name micro-app -d \
                         -p 5000:5000 \
                         ${{ vars.DOCKERHUB_USERNAME }}/micro-app:${{ github.sha }}
                   export IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' micro-app)
                   echo $IP
            - name: Build and push
              uses: docker/build-push-action@v5
              with:
                context: .
                push: true
                tags: ${{ vars.DOCKERHUB_USERNAME }}/micro-app:${{ github.sha }}

    
    
  

