name: Microservice pipeline
on:
    push
jobs:
    containerization:
        runs-on: ubuntu-latest
        steps:
            - name: checkout config files
              uses: actions/checkout@v2
            - name: docker hub login
              uses: docker/login-action@v3
              with:
                username: ${{ vars.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_PASSWORD }}

            - name: install Dependancies
              run: |
                    chmod +x install_dep.sh
                    ./install_dep.sh

            - name: Build and push
              uses: docker/build-push-action@v5
              with:
                  context: .
                  push: false
                  tags: ${{ vars.DOCKERHUB_USERNAME }}/micro-app:${{ github.sha }}
  
  
            - name: Docker image Test
              run: |
                   docker images
                   docker run --name micro-app -d \
                         -p 5000:5000 \
                         ${{ vars.DOCKERHUB_USERNAME }}/micro-app:${{ github.sha }}
                   export IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' micro-app)
                   echo $IP

           

    terraform:
        name: terraform deployment
        needs: containerization
        runs-on: ubuntu-latest
        steps:
            - name: checkout config files
              uses: actions/checkout@v2

            - name: setup terraform 
              uses: hashicorp/setup-terraform@v3.1.2

            - name: "Configure AWS Credentials" 
              uses: aws-actions/configure-aws-credentials@v4.0.2
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: us-west-2
          

            - name: Terraform init
              run: terraform init
              working-directory: ./Terraform

            - name: setup ssh private key
              run: |
                ls -la
                mkdir ~/.ssh
                
                echo "${{ secrets.ID_RSA }}" > ~/.ssh/id_rsa
                echo "${{ secrets.ID_RSA_PUB }}" > ~/.ssh/id_rsa.pub
                chmod 600 ~/.ssh/id_rsa
                chmod 600 ~/.ssh/id_rsa.pub
                ls -la ~/.ssh
                

            - name: validate
              run: terraform validate 
              
            - name: terraform apply
              run: terraform apply -auto-approve
              working-directory: ./terraform

            - name: terraform destroy
              run: terraform destroy
              working-directory: ./terraform
     
      