name: Microservice pipeline App
on:
  push:
    branches:
      - main


jobs:
  
  terraform:
    name: terraform deployment
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: checkout config files
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: setup terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.4
      - name: terraform destroy
        run: |
             terraform init -reconfigure 
             terraform destroy -auto-approve
        working-directory: ./Terraform

     
   
  