name: Microservice pipeline
on:
    push
jobs:
    containerization:
        runs-on: ubuntu-latest
        steps:
            - name: checkout config files
              uses: actions/checkout@v2
            - name: docker hub login
              uses: docker/login-action@v3
              with:
                username: ${{ vars.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_PASSWORD }}

            - name: Build and push
              uses: docker/build-push-action@v5
              with:
                  context: .
                  push: false
                  tags: ${{ vars.DOCKERHUB_USERNAME }}/microservice-test-app:${{ github.sha }}
  
  
            - name: Docker image Test
              run: |
                   docker images
                   docker run --name microservice-test-app -d \
                         -p 5000:5000 \
                         ${{ vars.DOCKERHUB_USERNAME }}/microservice-test-app:${{ github.sha }}
                   export IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' microservice-test-app)
                   echo $IP
      